### ISSUE TITLE
Emojis in post titles not supported.

### ISSUE THREAD

**Issue by person-al** [notkmhn/obyde#2]
Hey! I appreciate the frontmatter change you made recently to clean up how post content was parsed. I have noticed a small problem, though: the creation of the post no longer supports emojis in the metadata (e.g. title or category etc) like it used to. I suspect this has something to do with frontmatter.dumps, but I'm not sure.

**Comment by notkmhn** [comment]
Heyo, thanks for the report!
I haven't been able to reproduce the issue on my side using title, category, description and tags in the metadata section. Do you have a minimal sample that I can use to hunt down the problem?

**Comment by person-al** [comment]
It's possible that the problem isn't as much of a problem as I thought :thinking: . So I have [this post](https://person-al.github.io/%F0%9F%97%A8%EF%B8%8F/2021/07/07/decentralization-gets-eroded-by-stealth.html), which in my Obsidian vault looks like so:

```
---
layout: post
category: 🗨️
date: 2021-07-07
---
> decentralization gets eroded by stealth, often accidentally but usually irreversibly. We saw this with the evolution of the internet.
[source](https://www.coindesk.com/crypto-markets-bitcoin-lessons-coindesk)
```

_Previously_ in obyde, the resulting post would look like so...

```
---
layout: post
category: 🗨️
date: 2021-07-07
---
> decentralization gets eroded by stealth, often accidentally but usually irreversibly. We saw this with the evolution of the internet.
[source](https://www.coindesk.com/crypto-markets-bitcoin-lessons-coindesk)
```

With the new changes, the post markdown now looks like:
```
---
category: "\U0001F5E8️"
date: 2021-07-07
layout: post
---

> decentralization gets eroded by stealth, often accidentally but usually irreversibly. We saw this with the evolution of the internet.
[source](https://www.coindesk.com/crypto-markets-bitcoin-lessons-coindesk)
```

At first I was concerned that this change in category string was going to cause rendering problems down the line, but now that I'm looking at the `_site` folder, I can see that the html contains the emoji as expected:
```
<title>🗨️ Decentralization Gets Eroded By Stealth | Let’s get Person-al</title>
<meta name="generator" content="Jekyll v3.9.1" />
<meta property="og:title" content="🗨️ Decentralization Gets Eroded By Stealth" />
```

So I think we're okay. It's a little subpar from a readability perspective, but it's not a big deal. Thanks for looking into it and sorry for the false alarm.

**Comment by notkmhn** [comment]
No worries about the report, glad to hear that it's working regardless :)
